[18.0][MIG] mis_builder_budget: Migration to 18.0
OCA/mis-builder pull request #653
Opened 2024-12-03 03:17 UTC by chaule97

- Depends on: https://github.com/OCA/mis-builder/pull/652

2024-12-18 17:29 UTC, henrybackman approved these changes

2024-12-30 16:23 UTC, jbaudoux approved these changes
LGTM

2025-01-28 02:30 UTC, ryanc-me approved these changes

2025-04-27 16:24 UTC, Giuliano69 commented
Hi,
I  tried to install BOTH the 
mis_builder_budget end 
mis_builder

and MERGE them.
The process FAILED and  got a CONFLICT trying to merge the two different PC

Considering the two PR are two autonomous and distinct, how can I install and test them together ?

```
(venv18) odoo@Apollo11:~/18.0/addons/custom/chaule97$ git clone https://github.com/chaule97/mis-builder.git
Clone in 'mis-builder' in corso...
remote: Enumerating objects: 12829, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12829 (delta 9), reused 7 (delta 7), pack-reused 12814 (from 2)
Ricezione degli oggetti: 100% (12829/12829), 5.93 MiB | 8.55 MiB/s, fatto.
Risoluzione dei delta: 100% (9227/9227), fatto.
(venv18) odoo@Apollo11:~/18.0/addons/custom/chaule97$ cd mis-builder/
(venv18) odoo@Apollo11:~/18.0/addons/custom/chaule97/mis-builder$ git checkout 18.0-mig-mis_builder
ramo '18.0-mig-mis_builder' impostato per tracciare 'origin/18.0-mig-mis_builder'.
Si è passati a un nuovo branch '18.0-mig-mis_builder'
(venv18) odoo@Apollo11:~/18.0/addons/custom/chaule97/mis-builder$ git merge origin/18.0-mig-mis_builder_budget 
Merge automatico di .pre-commit-config.yaml in corso
CONFLITTO (contenuto): conflitto di merge in .pre-commit-config.yaml
Merge automatico di mis_builder_budget/models/mis_budget_item_abstract.py in corso
CONFLITTO (contenuto): conflitto di merge in mis_builder_budget/models/mis_budget_item_abstract.py
Merge automatico fallito; risolvi i conflitti ed esegui il commit
del risultato.
```

2025-04-27 17:47 UTC, chaule97 commented
you just clone origin repo and fetch into your local branch:

step 1: git clone https://github.com/OCA/mis-builder.git
step 2: git fetch origin pull/653/head:your_local_branch

2025-05-09 06:20 UTC, sbidoul commented
/ocabot migration mis_builder_budget

2025-05-14 07:12 UTC, BhaveshHeliconia commented
@chaule97: Can you please make runboat available so I can review it? As we need to use this module in a productive environment.

2025-05-15 03:41 UTC, z69426 commented
I've created a migration for the mis_builder_budget module to make it compatible with Odoo 18, and it's working properly. How can I submit this migration? https://github.com/z69426/mis_builder_budget.git

2025-06-02 10:43 UTC, sbidoul requested changes
Somehow `company_id` on budget by account items must remain a stored field. Not sure how to do that yet. I guess we can get inspiration from `account.move`.

2025-06-02 10:43 UTC, sbidoul commented on mis_builder_budget/models/mis_budget_by_account_item.py
> +        related="account_id.company_currency_id",
This is not correct, I think, because account_id.company_currency_id is non stored and context dependent.

2025-06-02 10:43 UTC, sbidoul commented on mis_builder_budget/models/mis_budget_by_account_item.py
> +    company_id = fields.Many2one("res.company", compute="_compute_company_id")
company_id must remain stored

2025-06-02 10:44 UTC, sbidoul commented on mis_builder_budget/models/mis_budget_by_account_item.py
> +        related="account_id.company_currency_id",
So since when `company_id` becomes stored again, this can become a related `company_id.currency_id`.

2025-06-02 14:35 UTC, sbidoul commented
Thanks for the quick reaction @chaule97 

A computed stored field cannot depend on the context, though.

I suggest the following
- make `company_id`  a regular non computed field with a default value
- make it visible in the budget items views
- add a constraint on company_id so it is one of the companies of the account_id
- add a company consistency check on account_id

2025-06-02 14:49 UTC, vdewulf commented
in direct from Cartagena, Spain, during the Spanish OCA Days

Tested MIS Builder Budget on v18 runboat in database with all modules installed.

There was no demo data because the demo data module was not migrated yet.

Steps:
- created a super basic template with one line with the expression: crd[4%]
- created a MIS report with the date range 2025 that I created on the fly, using the template from previous step
- displayed the report: the report shows the right amount based on the accounting items
- created a new budget (based on accounts)
- [bug] created a new item for this budget. Here, the Date range field doesn't show the already existing 2025 date range.
- Once a line is created and date range is set, it is then possible to find all the date ranges previously created.
- [bug2] created the 2025 date range from there, which opened a pop up showing "archived" on the right (see image). Why archived? When selecting a value on the "type" field, the archived word disappeared.
I created 2025 again but couldn't save it because it must be unique per company (which is logical) but could not find it from the budget item line. So created a quarter instead.
![Sélection_107](https://github.com/user-attachments/assets/3ea593f3-1f96-4748-a9bc-d2f0dc2c009a)


- adapted the mis report to have 2 columns in comparison mode, one with actuals, the other with the budget created previously. It works (actuals shows 127k, budget shows 500k) for the whole 2025 year.

- adapted the report to get a view on half a year only for the budget column by changing the date ranges to 31st May. The report displays now 206 849€, which is different from the 5/12 of 500 000€, I suppose the prorata temporis is based on days of the year.

==> CCL: bug with the date range selection to investigate. The rest seems to work alright from a general perspective for the budget by accounts; Budget by KPI's not tested.

2025-06-02 17:05 UTC, rov-adhoc commented
@chaule97 thanks for the PR!
Could you please remove the test-requirements.txt file? The dependency of mis_builder has already been merged. Thanks!

2025-06-03 13:26 UTC, sbidoul commented
I'll finish this in #690 

Thanks for this work!

2025-06-03 13:26 UTC, closed without merging